import React, { useState, useEffect } from "react";
import { Link, useLocation } from "react-router-dom";
import { useAuth } from "../components/AuthContext";

const Sidebar = () => {
    const location = useLocation();
    const { product, isLoggedIn } = useAuth(); // Get product and login status
    const [openSection, setOpenSection] = useState(null);

    const toggleSection = (title) => {
        setOpenSection(prev => (prev === title ? null : title));
    };

    // 1. Initial opening of the relevant section based on the current product/path
    useEffect(() => {
        if (location.pathname.startsWith('/ewaybill')) {
            // Find the main section title corresponding to the EWAY product
            const ewaySectionTitle = menuSections.find(s => s.product === 'EWAY')?.title;
            setOpenSection(ewaySectionTitle || null);
        } else if (location.pathname.startsWith('/einvoice')) {
            // Find the main section title corresponding to the EINVOICE product
            const einvoiceSectionTitle = menuSections.find(s => s.product === 'EINVOICE')?.title;
            setOpenSection(einvoiceSectionTitle || null);
        } else if (location.pathname === '/') {
             setOpenSection("Dashboard");
        }
    }, [location.pathname, product]); // Re-run effect when path changes or product changes

    // Helper function to check if any item in a section is active
    const isSectionActive = (section) => {
        const path = location.pathname;
        return section.items?.some(item => path.startsWith(item.path));
    };

    // 2. Define Menu Structure with NEW Nested Paths
    const menuSections = [
        // Login Links (Show only if not logged in)
        {
            title: "Login / Switch",
            items: [
                { path: "/ewaybill-login", label: "E-Way Bill Login" },
                { path: "/einvoice-login", label: "E-Invoice Login" },
            ],
            // Only show if the user is NOT logged into both products
            showCondition: !isLoggedIn || true, // Always show for switching/login
        },

        // Dashboard
        {
            title: "Dashboard",
            items: [{ path: "/", label: "Dashboard" }],
        },

        // -----------------------------------------------------------------
        // E-WAY BILL MODULES (Prefix: /ewaybill)
        // -----------------------------------------------------------------
        {
            title: "E-Way Bill Core",
            items: [
                { path: "/ewaybill/ewb-generate-print", label: "Generate & Print" },
                { path: "/ewaybill/fetch-ewb", label: "Fetch by EWB No" },
                { path: "/ewaybill/ewb-details", label: "Get EWB Details" },
            ],
            product: "EWAY",
        },
        {
            title: "EWB Print / Summary",
            items: [
                { path: "/ewaybill/ewb-print", label: "Print E-Way Bill" },
                { path: "/ewaybill/ewb-print-summary", label: "Print Summary" },
            ],
            product: "EWAY",
        },
        {
            title: "EWB Actions",
            items: [
                { path: "/ewaybill/actions", label: "Cancel/Reject EWB" },
                { path: "/ewaybill/update-transporter-id", label: "Update Transporter ID" },
            ],
            product: "EWAY",
        },
        {
            title: "Fetch EWB / Consignee",
            items: [
                // Path corrected based on assumed App.js route name
                { path: "/ewaybill/assigned-ewb", label: "Transporter EWB" }, 
                { path: "/ewaybill/consignee-ewb", label: "Consignee EWB" },
                { path: "/ewaybill/fetch-by-date", label: "Fetch by Date" },
            ],
            product: "EWAY",
        },
        {
            title: "EWB by Document",
            items: [
                { path: "/ewaybill/by-doc-type", label: "By Doc No & Type" },
                { path: "/ewaybill/generated-by-date", label: "Generated by Date" },
                { path: "/ewaybill/get-by-doc-no", label: "Get by Doc No" },
                { path: "/ewaybill/download-doc", label: "Doc Download" },
                { path: "/ewaybill/get-doc-status", label: "Doc Status" },
            ],
            product: "EWAY",
        },
        {
            title: "Multi-Vehicle / Consolidate",
            items: [
                { path: "/ewaybill/multi-vehicle-initiate", label: "Multi-Vehicle Initiate" },
                { path: "/ewaybill/consolidated-ewb-details", label: "Consolidated EWB Details" },
                { path: "/ewaybill/consolidate-ewb", label: "Consolidate EWB" },
            ],
            product: "EWAY",
        },

        // -----------------------------------------------------------------
        // E-INVOICE MODULES (Prefix: /einvoice)
        // -----------------------------------------------------------------
        {
            title: "E-Invoice Core",
            items: [
                { path: "/einvoice/generate-print", label: "Generate E-Invoice" },
                { path: "/einvoice/cancel-irn", label: "Cancel IRN" },
                { path: "/einvoice/get-by-irn", label: "Get by IRN" },
                { path: "/einvoice/get-by-doc", label: "Get IRN by Doc" },
            ],
            product: "EINVOICE",
        },
        {
            title: "EWB from IRN",
            items: [
                { path: "/einvoice/generate-ewb-by-irn", label: "Generate EWB" },
                { path: "/einvoice/cancel-ewb-by-irn", label: "Cancel EWB" },
                { path: "/einvoice/get-ewb-by-irn", label: "Get EWB" },
            ],
            product: "EINVOICE",
        },
        {
            title: "Print / View / Upload",
            items: [
                { path: "/einvoice/print-irn", label: "Print E-Invoice" },
                { path: "/einvoice/upload-invoices", label: "Upload Invoice" },
                { path: "/einvoice/uploaded-file-status", label: "Upload Status" },
                { path: "/einvoice/single-invoice-details", label: "Single Invoice" },
                { path: "/einvoice/list-of-invoices", label: "Invoice List" },
            ],
            product: "EINVOICE",
        },
    ];

    // 3. Filter menu sections based on logged-in product
    const filteredSections = menuSections.filter(
        (section) =>
            // Always show the section if it has no product dependency (like Dashboard)
            !section.product || 
            // Show Login/Switch section if showCondition is true
            (section.title === "Login / Switch" && section.showCondition) ||
            // Show section if the current product matches the section's product
            section.product === product
    );


    return (
        <div
            style={{
                width: 260, // Slightly increased width for readability
                background: "#1A73E8",
                color: "#fff",
                padding: 20,
                position: "sticky",
                top: 0,
                height: "100vh",
                overflowY: "auto",
                boxShadow: "4px 0 10px rgba(0,0,0,0.1)",
            }}
        >
            <h3 style={{ margin: "0 0 20px 0", textAlign: 'center' }}>
                IRIS API Portal 
                {product && <span style={{display: 'block', fontSize: '14px', color: '#B3E5FC'}}>({product})</span>}
            </h3>
            
            {filteredSections.map((section) => {
                // Determine if any link within the section is currently active
                const isActive = isSectionActive(section); 

                return (
                    <div key={section.title}>
                        <div
                            onClick={() => toggleSection(section.title)}
                            style={{
                                cursor: "pointer",
                                padding: "10px 8px",
                                fontWeight: "bold",
                                background: isActive || openSection === section.title ? "#2c84f8" : "transparent",
                                borderRadius: 6,
                                marginTop: 8,
                                transition: 'background 0.2s',
                                display: 'flex',
                                justifyContent: 'space-between',
                                alignItems: 'center',
                            }}
                        >
                            {section.title}
                            <span style={{ transform: openSection === section.title ? 'rotate(90deg)' : 'rotate(0deg)', transition: 'transform 0.2s' }}>
                                &gt; 
                            </span>
                        </div>

                        {/* Sub-menu Items */}
                        {(openSection === section.title || isActive) && // Keep open if active
                            <div style={{ maxHeight: openSection === section.title ? '500px' : '0', overflow: 'hidden', transition: 'max-height 0.3s ease-in-out' }}>
                                {section.items?.map((item) => (
                                    <Link
                                        key={item.path}
                                        to={item.path}
                                        style={{
                                            display: "block",
                                            padding: "8px 15px",
                                            marginTop: 4,
                                            borderRadius: 6,
                                            textDecoration: "none",
                                            fontSize: '14px',
                                            color: location.pathname.startsWith(item.path) ? "#1A73E8" : "#fff",
                                            background: location.pathname.startsWith(item.path) ? "#fff" : "transparent",
                                            transition: 'all 0.1s',
                                        }}
                                    >
                                        {item.label}
                                    </Link>
                                ))}
                            </div>
                        }
                    </div>
                );
            })}
        </div>
    );
};

export default Sidebar;