import React, { useState } from "react";
import { Link, useLocation } from "react-router-dom";

const Sidebar = () => {
  const location = useLocation();
  const [openSection, setOpenSection] = useState(null);

  const toggleSection = (title) => {
    setOpenSection(prev => (prev === title ? null : title));
  };

  const menuSections = [
    /* ───────── Dashboard ───────── */
    {
      title: "Dashboard",
      items: [{ path: "/", label: "Dashboard" }],
    },

    /* ───────── Login ───────── */
    {
      title: "Login",
      items: [
        { path: "/ewaybill-login", label: "E-Way Bill Login" },
        { path: "/einvoice-login", label: "E-Invoice Login" },
      ],
    },

    /* ───────── E-WAY BILL ───────── */
    { separator: true, heading: "E-Way Bill Modules" },

    {
      title: "EWB Generate & Print",
      items: [
        { path: "/ewb-generate-print", label: "Generate & Print" },
        { path: "/ewb-print", label: "Print E-Way Bill" },
        { path: "/ewb-print-summary", label: "Print Summary" },
      ],
    },

    {
      title: "EWB Actions",
      items: [
        { path: "/ewaybill-actions", label: "E-Way Bill Actions" },
        { path: "/update-transporter-id", label: "Update Transporter ID" },
      ],
    },

    {
      title: "Fetch E-Way Bill",
      items: [
        { path: "/consignee-ewaybill", label: "Consignee E-Way Bill" },
        { path: "/fetch-ewb-by-date", label: "Fetch by Date" },
        { path: "/transporter-ewaybill", label: "Transporter E-Way Bill" },
      ],
    },

    {
      title: "EWB by Document",
      items: [
        { path: "/ewaybill-by-doc-type", label: "By Doc No & Type" },
        { path: "/generated-ewb-by-date", label: "Generated by Date" },
        { path: "/get-ewb-by-doc-no", label: "Get by Doc No" },
        { path: "/get-ewb-doc-download", label: "Doc Download" },
        { path: "/get-ewb-doc-status", label: "Doc Status" },
      ],
    },

    {
      title: "Multi-Vehicle",
      items: [
        { path: "/multi-vehicle-initiate", label: "Initiate" },
        { path: "/multi-vehicle-add", label: "Add Vehicle" },
        { path: "/multi-vehicle-edit", label: "Edit Vehicle" },
        { path: "/multi-vehicle-group-details", label: "Group Details" },
        { path: "/multi-vehicle-requests", label: "Requests" },
      ],
    },

    /* ───────── E-INVOICE ───────── */
    { separator: true, heading: "E-Invoice Modules" },

    {
      title: "E-Invoice Core",
      items: [
        { path: "/einvoice-generate", label: "Generate E-Invoice" },
        { path: "/einvoice-cancel-irn", label: "Cancel IRN" },
        { path: "/einvoice-get-by-irn", label: "Get by IRN" },
        { path: "/einvoice-get-by-doc", label: "Get IRN by Doc" },
      ],
    },

    {
      title: "EWB from IRN",
      items: [
        { path: "/generate-ewb-by-irn", label: "Generate EWB" },
        { path: "/cancel-ewb-by-irn", label: "Cancel EWB" },
        { path: "/get-ewb-by-irn", label: "Get EWB" },
      ],
    },

    {
      title: "Print",
      items: [
        { path: "/print-e-invoice-irn", label: "Print E-Invoice" },
      ],
    },

    {
      title: "Upload Invoice",
      items: [
        { path: "/upload-invoices", label: "Upload Invoice" },
        { path: "/uploaded-file-status", label: "Upload Status" },
      ],
    },

    {
      title: "View Invoice",
      items: [
        { path: "/single-invoice-details", label: "Single Invoice" },
        { path: "/list-of-invoices", label: "Invoice List" },
      ],
    },
  ];

  return (
    <div
      style={{
        width: 240,
        background: "#1A73E8",
        color: "#fff",
        padding: 20,
        position: "sticky",
        top: 0,
        height: "100vh",
        overflowY: "auto",
      }}
    >
      {menuSections.map((section, index) => {
        if (section.separator) {
          return (
            <div key={index} style={{ margin: "10px 0", textAlign: "center" }}>
              <hr />
              <strong>{section.heading}</strong>
            </div>
          );
        }

        const isActive = section.items.some(
          item => location.pathname === item.path
        );

        return (
          <div key={section.title}>
            <div
              onClick={() => toggleSection(section.title)}
              style={{
                cursor: "pointer",
                padding: "8px",
                fontWeight: "bold",
                background: isActive ? "#2c84f8" : "transparent",
                borderRadius: 6,
              }}
            >
              {section.title}
            </div>

            {openSection === section.title &&
              section.items.map(item => (
                <Link
                  key={item.path}
                  to={item.path}
                  style={{
                    display: "block",
                    padding: "8px 15px",
                    marginTop: 4,
                    borderRadius: 6,
                    textDecoration: "none",
                    color:
                      location.pathname === item.path ? "#1A73E8" : "#fff",
                    background:
                      location.pathname === item.path ? "#fff" : "transparent",
                  }}
                >
                  {item.label}
                </Link>
              ))}
          </div>
        );
      })}
    </div>
  );
};

export default Sidebar;
